apiVersion: v1
kind: Secret
metadata:
  name: docker-secret
  namespace: argocd
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJha2FzaGthdHVyaSIsInBhc3N3b3JkIjoiYWthc2hsbXNkOTEwMTEiLCJlbWFpbCI6ImFrYXNoa2F0dXJpNzdAZ21haWwuY29tIn19fQ==
